---
- name: Load distro software install catalog
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../vars/software/{{ target_distro }}/install.yml"

- name: Install software catalog
  ansible.builtin.include_tasks: api_install_many.yml
  vars:
    software_items: "{{ software_install | default([]) }}"
