---
- name: Load distro software remove catalog
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../vars/software/{{ target_distro }}/remove.yml"

- name: Remove software catalog
  ansible.builtin.include_tasks: api_remove_many.yml
  vars:
    software_items: "{{ software_remove | default([]) }}"
