---
- name: Remove unwanted software
  ansible.builtin.import_tasks: remove_software.yml
  tags: [workstation, remove_software]

- name: Setup folders
  ansible.builtin.import_tasks: setup_folders.yml
  tags: [workstation, folders]

- name: Install generic software
  ansible.builtin.import_tasks: install_generic_software.yml
  tags: [workstation, generic_software]

- name: Setup desktop behavior
  ansible.builtin.import_tasks: setup_desktop.yml
  tags: [workstation, desktop]

- name: Setup display behavior
  ansible.builtin.import_tasks: setup_display.yml
  tags: [workstation, display]

- name: Setup specialized software
  ansible.builtin.import_tasks: setup_specialized_software.yml
  tags: [workstation, specialized_software]

- name: Setup configuration
  ansible.builtin.import_tasks: setup_configuration.yml
  tags: [workstation, configuration]

- name: Optimize system
  ansible.builtin.import_tasks: optimize.yml
  tags: [workstation, optimize]
