---
- name: Setup mise
  ansible.builtin.import_role:
    name: mise
  tags: [mise]

- name: Setup tmux
  ansible.builtin.import_role:
    name: tmux
  tags: [tmux]

- name: Setup LunarVim
  ansible.builtin.import_role:
    name: lunarvim
  tags: [lunarvim]

- name: Setup Android development
  ansible.builtin.import_role:
    name: android_dev
  tags: [android]

- name: Setup Docker
  ansible.builtin.import_role:
    name: docker
  tags: [docker]
