---
machine_profile: workstation

target_distro: fedora
desktop_environment: kde
display_server: wayland
dotfiles_profile: modern

confirm_workstation_setup: true
confirm_dotfiles_setup: true
confirm_backup: false
confirm_restore: false
confirm_nvidia_setup: false

dotfiles_repo_url: "https://github.com/Brunobrlk/dotfiles.git"

backup_restore_external_drive_mount: "/run/media/{{ ansible_user_id }}/Bruno"
backup_restore_source_name: backup-latest
backup_restore_source_path: "{{ backup_restore_external_drive_mount }}/{{ backup_restore_source_name }}"
