---
- name: Install backup dependencies
  ansible.builtin.include_role:
    name: software
    tasks_from: api_install_many
  vars:
    software_items: "{{ backup_dependencies }}"

- name: Load backup/restore catalog
  ansible.builtin.include_vars:
    file: "{{ backup_restore_catalog_file }}"

- name: Validate backup configuration
  ansible.builtin.import_tasks: validation.yml

- name: Backup items
  ansible.builtin.include_tasks: item.yml
  loop: "{{ backup_items_to_process | default([]) }}"
  loop_control:
    loop_var: item
    label: "{{ item.name | default(item.local | default('backup-item')) }}"
