---
all:
  children:
    vm_hosts:
      hosts:
        vm_host_local:
          ansible_connection: local
          ansible_host: localhost

    linux_vms:
      children:
        linux_desktop_vms:
        linux_server_vms:

    linux_desktop_vms:
      hosts:
        arch_desktop:
        fedora_desktop:

    linux_server_vms:
      hosts:
        debian_server:
        ubuntu_server:
        fedora_server:

    windows_vms:
      hosts:
        win11_base_backup:
        win11_workstudy:
        win11_testing:

    database_vms:
      hosts:
        debian_server:
