---
platformio_core_dir: "{{ ansible_user_dir }}/.platformio"
platformio_installer_url: "https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py"
platformio_installer_path: "/tmp/get-platformio.py"
platformio_udev_rules_url: "https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules"
platformio_udev_rules_path: "/etc/udev/rules.d/99-platformio-udev.rules"
platformio_user_bin_dir: "{{ ansible_user_dir }}/.local/bin"
platformio_shell_commands:
  - platformio
  - pio
  - piodebuggdb
platformio_environment:
  PATH: >-
    {{
      mise_environment.PATH
      if mise_environment is defined and mise_environment.PATH is defined
      else ansible_env.HOME ~ '/.local/share/mise/shims:' ~ ansible_env.PATH
    }}
