---
- name: Remove conflicting Docker packages on Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: Install DNF plugin dependency for Docker repository
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker Fedora repository
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: "0644"

- name: Install Docker Engine packages on Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
