---
- name: Back up local Linux libvirt VMs
  hosts: workstation
  connection: local
  gather_facts: true

  vars_files:
    - ../vars/vms/main.yml

  pre_tasks:
    - name: Validate VM backup target
      ansible.builtin.import_role:
        name: checkhost
      vars:
        checkhost_target: vms
      tags: [ always, checkhost ]

  roles:
    - role: vms_backup
