---
- name: Backup workstation data
  hosts: workstation
  gather_facts: true

  pre_tasks:
    - name: Validate backup target
      ansible.builtin.import_role:
        name: checkhost
      vars:
        checkhost_target: backup
      tags: [ always, checkhost ]

  roles:
    - role: backup
      tags: [ backup ]
