---
- name: Restore workstation data
  hosts: workstation
  gather_facts: true

  pre_tasks:
    - name: Validate restore target
      ansible.builtin.import_role:
        name: checkhost
      vars:
        checkhost_target: restore
      tags: [ always, checkhost ]

  roles:
    - role: restore
      tags: [ restore ]
