---
- name: Setup virtual machines on host
  hosts: workstation
  connection: local
  gather_facts: true

  vars_files:
    - ../vars/vms/main.yml

  pre_tasks:
    - name: Validate VM host target
      ansible.builtin.import_role:
        name: checkhost
      vars:
        checkhost_target: vms
      tags:
        - always
        - checkhost

  roles:
    - role: virtualization_host
      tags:
        - virtualization_host

    - role: vms_restore
      tags:
        - vms_restore
