---
- name: Setup developer workstation
  hosts: workstation
  gather_facts: true

  pre_tasks:
    - name: Validate workstation target
      ansible.builtin.import_role:
        name: checkhost
      vars:
        checkhost_target: workstation
      tags:
        - always
        - checkhost

  roles:
    - role: software
      tags: [ workstation, software ]

    - role: folders
      tags: [ workstation, folders ]

    - role: desktop
      tags: [ workstation, desktop ]

    - role: display
      tags: [ workstation, display ]

    - role: optimize
      tags: [ workstation, optimize ]

    - role: mise
      tags: [ workstation, mise ]

    - role: tmux
      tags: [ workstation, tmux ]

    - role: docker
      tags: [ workstation, docker ]
